### PR TITLE
Name translation route

### PR DESCRIPTION
**Pull request by otaviopace**
Added new route to the project: GET /:name/:language
This solves the second item of this issue: https://github.com/bluzi/name-db/issues/198

### CODE REVIEW

**Comment by otaviopace** [comment]
Ooops I've put the commit (Added name 'otavio') of my last pull request here because the master branch was not updated. I don't know if this will result in having two equal commits. Github says that 'This branch has no conflicts with the base branch'

**Comment by bluzi** [comment]
As to the unnecessary commit - Don't worry about it. :)

**Comment by otaviopace** [comment]
I agree with you, those changes would definetly improve the API. I will do it when I have some free time :)
I just have one question, why is the decision of using a database if the entries of the names are in files inside of the project. Another thing that I was thinking about is that if we want more data (names info) we should use a different approach. I am talking about something like a form that anyone can contribute instead of a pull request that only developees can help. Another approach would be use web crawlers on web sites that have info on names, like those "dictionary of names". Tell me more about this project, I don't know if this is the right place though haha

**Comment by bluzi** [comment]
Hey @otaviopace,

> I agree with you, those changes would definetly improve the API. I will do it when I have some free time :)
Thanks!

> I just have one question, why is the decision of using a database if the entries of the names are in files inside of the project?
It's faster to read data from a database than reading it from a JSON file

> Another thing that I was thinking about is that if we want more data (names info) we should use a different approach. I am talking about something like a form that anyone can contribute instead of a pull request that only developers can help.
It came up a few times around here. I assume we can create something like that, but I'd like to preserve the versioning capabilities of Git, and the "approval" system of GitHub's pull requests. Maybe we could create a form that integrates with GitHub.

> Another approach would be to use web crawlers on web sites that have info on names, like those "dictionary of names"
@EmilLuta is doing something like that [here](https://github.com/bluzi/name-db/issues/95)
Feel free to join aboard and help him

>  Tell me more about this project and what direction you want to take on it, I don't know if this is the right place though haha
I'm trying to create a collection of names in all languages. I guess a common use case would be, for instance, the ability to translate names accurately in website profiles. (for example in forums) 

Feel free to ask if you have any more questions

**Comment by otaviopace** [comment]
I have made a big mistake by using rebase to update my branch, I will close this Pull Request and open a fresh new one putting the changes that you requested :)

**Pull request closed without merging**
