### PR TITLE
Add name "Jesus"

### PR DESCRIPTION
**Pull request by CodeWritingCow**
Hello, I'd like to add the name "Jesus" to the name collection

### CODE REVIEW

**Comment by bluzi** [comment]
Hi @CodeWritingCow,

Thanks!
The tests are failing because you add a translation for `zho + 13`. Not sure what you've meant by that, but that's not a valid ISO language code.

Please change it, and I'll gladly merge your PR once the tests pass. :)

**Comment by CodeWritingCow** [comment]
Sorry @bluzi! I fixed the ISO code. It's for Chinese.

**Comment by bluzi** [comment]
Nice, one more thing: all translations should be spelled using lowercase letters.

**Comment by bluzi** [comment]
Awesome, thank you for the effort :) merged #1

**Comment by CodeWritingCow** [comment]
Thanks for your patience @bluzi!

**Comment by bluzi** [comment]
Hey, no problem! Thank you for your contribution, you're the hero here :)

**Pull request merged**
