### PR TITLE
Added name "varun"

### PR DESCRIPTION
**Pull request by varun560**

### CODE REVIEW

**Comment by bluzi** [comment]
hi @varun560, looks like you have a missing comma there, that's why the tests failed.

**Comment by varun560** [comment]
i am a beginner and i dont really dont understood it pls help

**Comment by bluzi** [comment]
Don't worry about it, fixed it for you. 

Thanks!

**Comment by varun560** [comment]
thanks for the assist @bluzi

**Comment by bluzi** [comment]
You're welcome :) merged #1

**Pull request merged**
