### PR TITLE
Add new name Vishwas to names.json

### PR DESCRIPTION
**Pull request by vsc-github**
Adding new name "Vishwas" to names.json with two translations for "eng" & "hin".

### CODE REVIEW

**Comment by bluzi** [comment]
Thanks! 

Please don't include English translation in the translations object. The English name already appears in the `name` field.
Remove the English translation, and I'll merge it

**Comment by bluzi** [comment]
you're the best :) thanks! 
merged #1

**Comment by vsc-github** [comment]
@bluzi Thanks mate. I also noticed a few names had english translations included in the translations object. Should I open an issue to remove them and submit a PR?

**Comment by bluzi** [comment]
sure :) 
you can also add a test if you want to, so PRs with English translations will fail automatically.

**Comment by vsc-github** [comment]
Cool. I just fixed the names, now I'll add the validation test.

**Pull request merged**
