### PR TITLE
Contribute to Hacktoberfest

### PR DESCRIPTION
**Pull request by KLMarcos**

### CODE REVIEW

**Comment by mytreexx** [comment]
@bluzi lower case "д" in the translation tests as uppercase.

**Comment by arminkhoshbin** [comment]
@mytreexx I don't see anything wrong with the translation. It looks fine. The failing build might be because master was broken but it's fixed now. I can't seem to be able to merge latest master into his branch now though so another Travis build can kick off.

**Comment by bluzi** [comment]
I restarted the build, lets see if it'll pass now
@arminkhoshbin @mytreexx

**Comment by bluzi** [comment]
Yup, all good. 
Must be because the `master` was broken. 

Merging #87

**Pull request merged**
