### PR TITLE
Create felipe.json

### PR DESCRIPTION
**Pull request by JansleyFelipe**
added my json

### CODE REVIEW

**Comment by bluzi** [comment]
hi @JansleyFelipe, thanks!
the tests are failing because you included an English translation. please remove it and i'll be able to merge.
thanks!

**Comment by bluzi** [comment]
hi, now it seems to fail because you wrote the name with a capital F. all names should be lowercase.

**Comment by bluzi** [comment]
nvm, i fixed it. thank you!
megred #1

**Comment by JansleyFelipe** [comment]
Ok, Thanks bro

**Pull request merged**
