### PR TITLE
#452 Add a Logo

### PR DESCRIPTION
**Pull request by StegSchreck**

### CODE REVIEW

**Comment by bluzi** [comment]
Hey man, not sure what you were trying to do there with the logo, but the link is not found:
https://github.com/bluzi/name-db/blob/master/logo.png

**Comment by StegSchreck** [comment]
It will be working as soon as the pr is merged. But please have a look at it before that

**Comment by bluzi** [comment]
Whoops, you're right. :) Missed that you've already committed it. 
Looks good, thanks a lot!

**Comment by StegSchreck** [comment]
you're welcome ;)

**Pull request merged**
