### PR TITLE
Add test for valid ISO-639-3 language codes in translations

### PR DESCRIPTION
**Pull request by chrisf**

### CODE REVIEW

**Comment by chrisf** [comment]
The test fails because there's a few invalid language codes in some of the name files

**Comment by bluzi** [comment]
Awesome! 
Can you fix the codes so the test won't fail? I'll merge it right after.

**Comment by chrisf** [comment]
Someone else might want to double check that I got the language codes correct

**Comment by bluzi** [comment]
No worries, I'll review it

**Comment by bluzi** [comment]
megred #40 

Thanks again, @chrisf :)

**Pull request merged**
