### PR TITLE
Added the Igbo name Chizi

### PR DESCRIPTION
**Pull request by cezennia**
Added the igbo name chizi to \collections

### CODE REVIEW

**Comment by bluzi** [comment]
Hey @cezennia,

Thanks, however, the tests are failing because your translations contain capital letters.
Also, the Hebrew translation should be spelled using the Hebrew alphabet.

Please make the changes and I'll merge your PR

**Comment by bluzi** [comment]
That's not the correct Hebrew translation.
You can also remove the Hebrew translation and I'll merge it.

**Comment by cezennia** [comment]
adjusted the hebrew translation and Capitalization issues

**Comment by bluzi** [comment]
Cool, thanks!
merged #1

**Pull request merged**
