### PR TITLE
Vrunda - Meaning Basil

### PR DESCRIPTION
**Pull request by vrundakansara**

### CODE REVIEW

**Comment by vrundakansara** [comment]
Issue - #1

**Comment by bluzi** [comment]
hi @vrundakansara, thank you for your contribution! 
however, it seems like some test failed for you PR, probably because the JSON structure is broken. 

please fix the JSON issues and i'll merge it once the tests will pass :)

**Comment by vrundakansara** [comment]
Hi @bluzi !

Please check the recent commit. Seems like now things are fixed. Thank you for your heads up! :)

**Comment by bluzi** [comment]
and thank you for your contribution :) 
merged as promised

**Pull request merged**
