### PR TITLE
Create kshitij.json

### PR DESCRIPTION
**Pull request by dashan124**
New name Kshitij added

### CODE REVIEW

**Comment by bluzi** [comment]
hi, @dashan124, please create a single PR and add all the names you want :)

**Comment by dashan124** [comment]
How to add two many files in one PR

**Comment by bluzi** [comment]
Fork the repository, add as many files as you wish and make as many changes as you want, and then create a PR

**Comment by bluzi** [comment]
anyway, merged :) thanks!
#1

**Pull request merged**
